Create variable about number of conflicts in previous month
<hr>

In [1]:
# import necessary packages
import numpy as np
import pandas as pd
import os

# set working directory
os.chdir("/Users/varvarailyina/hertie/ML/US_conflict_forecasting/")

In [2]:
# load clean conflict data
df_acled_clean = pd.read_csv("./Dataset/ConflictDataClean.csv")

# look at data
df_acled_clean.head()

    ZCTA event_MY  admin2  fatalities  event_count
0  15001  2022-01  Beaver           0            1
1  15001  2022-02  Beaver           0            0
2  15001  2022-03  Beaver           0            0
3  15001  2022-04  Beaver           0            0
4  15001  2022-05  Beaver           0            0

In [3]:
# load clean data with all PA zip codes and counties
df_all_clean = pd.read_csv("./Dataset/create_acs_conflict/acs_conflict.csv")

# look at data
df_all_clean.head()

,ZCTA,Month,Name,"Population, 2020","# Square Land Miles, 2020","Population per Square Land Mile, 2022",Rural_Urban_Commerical,"Total Population, 2022","Median age, 2022","<18 Years Old, 2022",...,"Asian, Not Hispanic or Latino, 2022","Other Races, Not Hispanic or Latino, 2022","Two or more races, 2022","Hispanic or Latino (Any Race), 2022","Poverty Rate, 2022",ZCTA.1,month,admin2,fatalities,event_count
0,15001.0,2022-01,"Aliquippa, PA",32299.0,60.348429,535.208629,Urban,32237.0,47.5,0.169153,...,0.006359,0.001396,0.04166,0.025313,0.104669,15001.0,2022-01,Beaver,0.0,1.0
1,15001.0,2022-02,"Aliquippa, PA",32299.0,60.348429,535.208629,Urban,32237.0,47.5,0.169153,...,0.006359,0.001396,0.04166,0.025313,0.104669,15001.0,2022-02,Beaver,0.0,0.0
2,15001.0,2022-03,"Aliquippa, PA",32299.0,60.348429,535.208629,Urban,32237.0,47.5,0.169153,...,0.006359,0.001396,0.04166,0.025313,0.104669,15001.0,2022-03,Beaver,0.0,0.0
3,15001.0,2022-04,"Aliquippa, PA",32299.0,60.348429,535.208629,Urban,32237.0,47.5,0.169153,...,0.006359,0.001396,0.04166,0.025313,0.104669,15001.0,2022-04,Beaver,0.0,0.0
4,15001.0,2022-05,"Aliquippa, PA",32299.0,60.348429,535.208629,Urban,32237.0,47.5,0.169153,...,0.006359,0.001396,0.04166,0.025313,0.104669,15001.0,2022-05,Beaver,0.0,0.0

In [4]:
# generate function to create binary variable if conflict in previous month in same zip code

def check_prev_month_conflict(df):
    
    # sort df by month
    df.sort_values(by='Month', inplace=True)
    
    # empty list to store result
    event_count_prev = []

    # for loop per row
    for index, row in df.iterrows():
        
        # vars with current month and year
        current_month = row['Month']
        
        # calculate previous month
        prev_year, prev_month = current_month.split('-')
        prev_month = str(int(prev_month) - 1).zfill(2)
        
        if prev_month == '00':
            prev_year = str(int(prev_year) - 1)
            prev_month = '12'

        prev_month = f"{prev_year}-{prev_month}"

        # check if previous month exists in df
        prev_month_tmp = df[df['Month'] == prev_month]

        # check if previous month had a conflict
        if not prev_month_tmp.empty:
            previous_month_event_num = prev_month_tmp.iloc[0]['event_count']
            event_count_prev.append(previous_month_event_num)

        # if no previous month, assume no conflict
        else:
            event_count_prev.append(0)

    # append result to new var
    df['event_count_prev'] = event_count_prev
    #df.loc[:, 'event_count_prev'] = event_count_prev

    return df

In [10]:
# run function on df
df_out = check_prev_month_conflict(df_all_clean)

In [11]:
# look at zip codes with repeated conflicts
df_out[(df_out['event_count'] > 0) & (df_out['event_count_prev'] > 0)]

,ZCTA,Month,Name,"Population, 2020","# Square Land Miles, 2020","Population per Square Land Mile, 2022",Rural_Urban_Commerical,"Total Population, 2022","Median age, 2022","<18 Years Old, 2022",...,"Other Races, Not Hispanic or Latino, 2022","Two or more races, 2022","Hispanic or Latino (Any Race), 2022","Poverty Rate, 2022",ZCTA.1,month,admin2,fatalities,event_count,event_count_prev
14437,17837.0,2022-02,"Lewisburg, PA",18734.0,56.191610,333.394969,Urban,18670.0,36.7,0.146010,...,0.002035,0.008409,0.065667,0.114748,17837.0,2022-02,Union,0.0,1.0,1.0
21589,19530.0,2022-02,"Kutztown, PA",14830.0,54.605110,271.586301,Rural,14616.0,25.8,0.113506,...,0.000000,0.023810,0.065818,0.110174,19530.0,2022-02,Berks,0.0,1.0,1.0
12745,17331.0,2022-02,"Hanover, PA",55458.0,74.417671,745.226229,Urban,54942.0,41.6,0.219559,...,0.002730,0.024389,0.074060,0.074664,17331.0,2022-02,York,0.0,1.0,1.0
9685,16801.0,2022-02,"State College, PA",42446.0,31.001484,1369.160245,Urban,43307.0,26.3,0.121020,...,0.001847,0.036022,0.034244,0.302329,16801.0,2022-02,Centre,0.0,1.0,1.0
2293,15370.0,2022-02,"Waynesburg, PA",14153.0,148.179072,95.512813,Rural,13886.0,43.5,0.158793,...,0.005545,0.059628,0.023909,0.113571,15370.0,2022-02,Greene,0.0,1.0,1.0
1405,15219.0,2022-02,"Pittsburgh, PA",10949.0,2.200628,4975.398539,Urban,10680.0,32.4,0.220412,...,0.007303,0.043446,0.039232,0.346298,15219.0,2022-02,Allegheny,0.0,10.0,1.0
7765,16335.0,2022-02,"Meadville, PA",27452.0,114.510875,239.732690,Rural,27497.0,42.9,0.189402,...,0.000618,0.034222,0.015129,0.114554,16335.0,2022-02,Crawford,0.0,1.0,1.0
18697,18901.0,2022-02,"Doylestown, PA",28395.0,20.970946,1354.016198,Urban,28311.0,46.7,0.193670,...,0.005051,0.041044,0.026527,0.040835,18901.0,2022-02,Bucks,0.0,1.0,1.0
20029,19107.0,2022-02,"Philadelphia, PA",17600.0,0.544015,32352.025246,Urban,15232.0,31.1,0.055869,...,0.003611,0.051339,0.061909,0.217631,19107.0,2022-02,Philadelphia,0.0,9.0,1.0
15625,18042.0,2022-02,"Easton, PA",44026.0,22.113366,1990.922578,Urban,44818.0,36.7,0.203847,...,0.010398,0.055201,0.202865,0.123315,18042.0,2022-02,Northampton,0.0,1.0,1.0
8449,16501.0,2022-02,"Erie, PA",2241.0,0.715769,3130.899999,Urban,1670.0,53.7,0.019162,...,0.004192,0.016168,0.058084,0.615658,16501.0,2022-02,Erie,0.0,2.0,1.0
11773,17102.0,2022-02,"Harrisburg, PA",7989.0,0.757464,10547.033531,Urban,8173.0,34.8,0.137526,...,0.013337,0.034504,0.125535,0.260831,17102.0,2022-02,Dauphin,0.0,7.0,1.0
5089,15767.0,2022-02,"Punxsutawney, PA",14501.0,159.969141,90.648733,Rural,14156.0,43.8,0.214679,...,0.005298,0.012927,0.005369,0.167732,15767.0,2022-02,Jefferson,0.0,1.0,1.0
8953,16648.0,2022-02,"Hollidaysburg, PA",15149.0,60.046020,252.289827,Rural,14547.0,49.4,0.172750,...,0.000000,0.013061,0.005499,0.067206,16648.0,2022-02,Blair,0.0,1.0,1.0
16969,18360.0,2022-02,"Stroudsburg, PA",29079.0,86.487653,336.221401,Urban,29345.0,45.5,0.198944,...,0.009303,0.031351,0.173386,0.094239,18360.0,2022-02,Monroe,0.0,1.0,1.0
845,15090.0,2022-06,"Wexford, PA",24985.0,21.867901,1142.542210,Urban,24964.0,39.7,0.245754,...,0.003405,0.030484,0.050953,0.053435,15090.0,2022-06,Allegheny,0.0,1.0,1.0
8453,16501.0,2022-06,"Erie, PA",2241.0,0.715769,3130.899999,Urban,1670.0,53.7,0.019162,...,0.004192,0.016168,0.058084,0.615658,16501.0,2022-06,Erie,0.0,6.0,1.0
1409,15219.0,2022-06,"Pittsburgh, PA",10949.0,2.200628,4975.398539,Urban,10680.0,32.4,0.220412,...,0.007303,0.043446,0.039232,0.346298,15219.0,2022-06,Allegheny,0.0,9.0,1.0
77,15009.0,2022-06,"Beaver, PA",15594.0,23.307568,669.053082,Urban,15722.0,45.1,0.220201,...,0.002417,0.015965,0.016219,0.069796,15009.0,2022-06,Beaver,0.0,2.0,1.0
3653,15601.0,2022-06,"Greensburg, PA",57141.0,80.646968,708.532527,Urban,55917.0,46.1,0.168911,...,0.001019,0.025735,0.013735,0.090765,15601.0,2022-06,Westmoreland,0.0,2.0,1.0
6845,16137.0,2022-06,"Mercer, PA",12654.0,108.530224,116.594250,Rural,12710.0,44.3,0.170653,...,0.002911,0.021558,0.014870,0.125574,16137.0,2022-06,Mercer,0.0,1.0,1.0
9689,16801.0,2022-06,"State College, PA",42446.0,31.001484,1369.160245,Urban,43307.0,26.3,0.121020,...,0.001847,0.036022,0.034244,0.302329,16801.0,2022-06,Centre,0.0,1.0,1.0
4517,15701.0,2022-06,"Indiana, PA",30269.0,112.216651,269.737153,Rural,30941.0,36.2,0.152193,...,0.003458,0.026308,0.015998,0.146919,15701.0,2022-06,Indiana,0.0,1.0,1.0
8177,16415.0,2022-06,"Fairview, PA",9898.0,23.338376,424.108345,Urban,10051.0,43.2,0.246045,...,0.009452,0.020098,0.034325,0.035026,16415.0,2022-06,Erie,0.0,1.0,1.0
5633,15901.0,2022-06,"Johnstown, PA",3379.0,1.525868,2214.477605,Urban,3616.0,46.9,0.186947,...,0.010232,0.067478,0.103982,0.389603,15901.0,2022-06,Cambria,0.0,1.0,1.0
2297,15370.0,2022-06,"Waynesburg, PA",14153.0,148.179072,95.512813,Rural,13886.0,43.5,0.158793,...,0.005545,0.059628,0.023909,0.113571,15370.0,2022-06,Greene,0.0,1.0,1.0
6821,16134.0,2022-06,"Jamestown, PA",3498.0,47.452237,73.716230,Rural,3890.0,51.6,0.179692,...,0.004370,0.012082,0.009512,0.131973,16134.0,2022-06,Mercer,0.0,1.0,1.0
16085,18102.0,2022-06,"Allentown, PA",51567.0,2.981979,17292.876812,Urban,51640.0,30.5,0.305112,...,0.002576,0.016421,0.702789,0.291833,18102.0,2022-06,Lehigh,0.0,4.0,1.0
21233,19460.0,2022-06,"Phoenixville, PA",43611.0,34.529026,1263.024339,Urban,43246.0,37.9,0.194769,...,0.001249,0.036766,0.048213,0.059760,19460.0,2022-06,Chester,0.0,1.0,1.0
21593,19530.0,2022-06,"Kutztown, PA",14830.0,54.605110,271.586301,Rural,14616.0,25.8,0.113506,...,0.000000,0.023810,0.065818,0.110174,19530.0,2022-06,Berks,0.0,1.0,1.0
21977,19610.0,2022-06,"Reading, PA",16024.0,7.087316,2260.940372,Urban,16401.0,46.5,0.166758,...,0.000244,0.042010,0.098653,0.043108,19610.0,2022-06,Berks,0.0,1.0,1.0
11777,17102.0,2022-06,"Harrisburg, PA",7989.0,0.757464,10547.033531,Urban,8173.0,34.8,0.137526,...,0.013337,0.034504,0.125535,0.260831,17102.0,2022-06,Dauphin,0.0,20.0,1.0
18161,18657.0,2022-06,"Tunkhannock, PA",10793.0,118.163648,91.339428,Rural,11080.0,45.6,0.199819,...,0.000993,0.013357,0.019134,0.107661,18657.0,2022-06,Wyoming,0.0,1.0,1.0
21257,19464.0,2022-06,"Pottstown, PA",48409.0,25.638467,1888.139411,Urban,47913.0,38.1,0.227412,...,0.001398,0.054787,0.080980,0.117492,19464.0,2022-06,Montgomery,0.0,2.0,1.0
16157,18201.0,2022-06,"Hazleton, PA",31310.0,17.469596,1792.256693,Urban,31519.0,37.9,0.236905,...,0.004822,0.003744,0.593261,0.252153,18201.0,2022-06,Luzerne,0.0,1.0,1.0
18197,18701.0,2022-06,"Wilkes Barre, PA",4658.0,0.501502,9288.089618,Urban,3710.0,22,0.018868,...,0.008895,0.033693,0.094609,0.257269,18701.0,2022-06,Luzerne,0.0,2.0,1.0
21881,19601.0,2022-06,"Reading, PA",35477.0,3.761876,9430.666181,Urban,36003.0,31.7,0.292059,...,0.010444,0.026192,0.673944,0.322846,19601.0,2022-06,Berks,0.0,1.0,1.0
20033,19107.0,2022-06,"Philadelphia, PA",17600.0,0.544015,32352.025246,Urban,15232.0,31.1,0.055869,...,0.003611,0.051339,0.061909,0.217631,19107.0,2022-06,Philadelphia,1.0,32.0,1.0
17633,18503.0,2022-06,"Scranton, PA",1792.0,0.473890,3781.471261,Urban,1303.0,39.1,0.020721,...,0.013047,0.015349,0.061397,0.321739,18503.0,2022-06,Lackawanna,0.0,3.0,1.0
14285,17815.0,2022-06,"Bloomsburg, PA",28936.0,125.712112,230.176708,Rural,29125.0,33.9,0.164429,...,0.007657,0.013562,0.041957,0.196723,17815.0,2022-06,Columbia,0.0,2.0,1.0
19601,19047.0,2022-06,"Langhorne, PA",35452.0,17.248938,2055.314927,Urban,33874.0,44.6,0.181378,...,0.020783,0.031381,0.040119,0.063763,19047.0,2022-06,Bucks,0.0,1.0,1.0
14873,17901.0,2022-06,"Pottsville, PA",22608.0,79.422368,284.655326,Rural,22875.0,43.9,0.210667,...,0.003716,0.016437,0.047432,0.160085,17901.0,2022-06,Schuylkill,0.0,1.0,1.0
21137,19440.0,2022-06,"Hatfield, PA",19683.0,11.337688,1736.068305,Urban,19897.0,39.6,0.216616,...,0.000955,0.032015,0.063778,0.035368,19440.0,2022-06,Montgomery,0.0,1.0,1.0
10841,17013.0,2022-06,"Carlisle, PA",36578.0,39.189441,933.363666,Urban,36942.0,37.9,0.196633,...,0.003330,0.028423,0.065237,0.130207,17013.0,2022-06,Cumberland,0.0,2.0,1.0
18701,18901.0,2022-06,"Doylestown, PA",28395.0,20.970946,1354.016198,Urban,28311.0,46.7,0.193670,...,0.005051,0.041044,0.026527,0.040835,18901.0,2022-06,Bucks,0.0,1.0,1.0
20945,19380.0,2022-06,"West Chester, PA",50692.0,30.466894,1663.838780,Urban,50494.0,43.1,0.192914,...,0.000238,0.035291,0.046005,0.045566,19380.0,2022-06,Chester,0.0,1.0,1.0
13649,17579.0,2022-06,"Strasburg, PA",6662.0,14.642860,454.965763,Urban,6409.0,42,0.278983,...,0.000000,0.021376,0.019972,0.080276,17579.0,2022-06,Lancaster,0.0,1.0,1.0
16973,18360.0,2022-06,"Stroudsburg, PA",29079.0,86.487653,336.221401,Urban,29345.0,45.5,0.198944,...,0.009303,0.031351,0.173386,0.094239,18360.0,2022-06,Monroe,0.0,2.0,1.0
19721,19063.0,2022-06,"Media, PA",38338.0,25.099281,1527.454115,Urban,37716.0,45.2,0.181912,...,0.008140,0.023810,0.018348,0.035021,19063.0,2022-06,Delaware,0.0,1.0,1.0
13709,17602.0,2022-06,"Lancaster, PA",52665.0,24.562727,2144.102356,Urban,50184.0,37.4,0.224115,...,0.000538,0.022696,0.289176,0.128275,17602.0,2022-06,Lancaster,0.0,2.0,1.0
13409,17543.0,2022-06,"Lititz, PA",45320.0,65.956051,687.124223,Urban,45393.0,43.8,0.218448,...,0.002820,0.022537,0.053400,0.050288,17543.0,2022-06,Lancaster,0.0,1.0,1.0
13385,17538.0,2022-06,"Landisville, PA",7064.0,4.132154,1709.520202,Urban,7496.0,51.3,0.178762,...,0.000000,0.025080,0.088447,0.013506,17538.0,2022-06,Lancaster,0.0,1.0,1.0
21029,19406.0,2022-06,"King Of Prussia, PA",28553.0,13.443792,2123.879913,Urban,28826.0,36.2,0.182890,...,0.006244,0.028342,0.033685,0.038155,19406.0,2022-06,Montgomery,0.0,2.0,1.0
15485,18018.0,2022-06,"Bethlehem, PA",32388.0,5.172038,6262.134697,Urban,31479.0,38.2,0.162172,...,0.006957,0.023952,0.270530,0.184373,18018.0,2022-06,Northampton,0.0,2.0,1.0
15629,18042.0,2022-06,"Easton, PA",44026.0,22.113366,1990.922578,Urban,44818.0,36.7,0.203847,...,0.010398,0.055201,0.202865,0.123315,18042.0,2022-06,Northampton,0.0,1.0,1.0
20993,19401.0,2022-06,"Norristown, PA",43414.0,6.150964,7058.081170,Urban,42908.0,35.4,0.233290,...,0.005826,0.077678,0.235807,0.168304,19401.0,2022-06,Montgomery,0.0,2.0,1.0

In [12]:
# check that it worked
df_out[df_out['Name'] == "King Of Prussia, PA"][['ZCTA', 'Month', 'event_count', 'event_count_prev']]

          ZCTA    Month  event_count  event_count_prev
21024  19406.0  2022-01          0.0               0.0
21025  19406.0  2022-02          0.0               1.0
21026  19406.0  2022-03          0.0               0.0
21027  19406.0  2022-04          0.0               0.0
21028  19406.0  2022-05          1.0               0.0
21029  19406.0  2022-06          2.0               1.0
21030  19406.0  2022-07          0.0               0.0
21031  19406.0  2022-08          0.0               0.0
21032  19406.0  2022-09          0.0               0.0
21033  19406.0  2022-10          0.0               0.0
21034  19406.0  2022-11          0.0               0.0
21035  19406.0  2022-12          0.0               0.0

<br>
**when certain that changes are correct, edit the name of the `.csv` file below to overwrite the `acs_conflict.csv`

In [13]:
# order df
df_sorted = df_out.sort_values(by = ['ZCTA', 'Month'])

# save df
df_sorted.to_csv("./Dataset/create_acs_conflict/acs_conflict_varv.csv", index = False)
#df.to_csv("./Dataset/create_acs_conflict/acs_conflict.csv", index = False)